[global]
# Configuración global de Streamlit

# Tema de la aplicación
theme.primaryColor = "#1f77b4"
theme.backgroundColor = "#ffffff"
theme.secondaryBackgroundColor = "#f0f2f6"
theme.textColor = "#262730"
theme.font = "sans serif"

[server]
# Configuración del servidor
port = 8501
address = "localhost"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Configuración del navegador
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[logger]
# Configuración de logging
level = "info"
messageFormat = "%(asctime)s %(levelname)s: %(message)s"

[client]
# Configuración del cliente
caching = true
displayEnabled = true
showErrorDetails = true

[runner]
# Configuración del runner
magicEnabled = true
installTracer = false
fixMatplotlib = true

[mapbox]
# Token de Mapbox (opcional, para mapas)
token = ""

[deprecation]
# Configuraciones de deprecación
showfileUploaderEncoding = false
showPyplotGlobalUse = false